### ISSUE TITLE
Finding route

### ISSUE THREAD

**Issue by Ogochi** [tosi3k/io#1]
Problem with: station_a=Plac Wileński, station_b=Park Kultury Powsin

**Comment by tosi3k** [comment]
It seems that the Nextbike API only outputs stations with positive number of bikes - the old XML I parsed (when creating Django models of stations) doesn't contain Powsin as well as some other stations.

Can't think of a quick bugfix - we need to add missing stations to the database with matching routes (scraping Veturilo website station table && patching might be an option)

**Comment by tosi3k** [comment]
@MateuszOlko jakoś na dniach dodam brakujące stacje, dasz radę dopatchować trasy?

**Comment by MateuszOlko** [comment]
Jasne, tylko daj znać kiedy.

**Comment by tosi3k** [comment]
Wrzuciłem stacje do bazki.

**Comment by tosi3k** [comment]
Krawędzie też wrzucone, zamykam.
